version: '3.3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.3
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "max_connections=$PG__MAX_CONNECTIONS"
      - "-c"
      - "shared_buffers=$PG__SHARED_BUFFERS"
      - "-c"
      - "effective_cache_size=$PG__EFFECTIVE_CACHE_SIZE"
      - "-c"
      - "work_mem=$PG__WORK_MEM"
      - "-c"
      - "maintenance_work_mem=$PG__MAINTENANCE_WORK_MEM"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=$PG__TEMP_FILE_LIMIT"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_USER: $DB__USER
      POSTGRES_PASSWORD: $DB__PASSW
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./build/init_psql:/docker-entrypoint-initdb.d
      - $PG__DATA:/var/lib/postgresql/data
    ports:
      - "$PG__PORT:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G