version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper
    container_name: zookeeper
    env_file:
      - .env
    ports:
      - "$ZOOKEEPER__PORT:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      #start_period: 10s
      retries: 20
      interval: 10s
  
  broker:
    image: confluentinc/cp-kafka:7.5.3
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "$KAFKA_EXT__PORT:29092"
      - "$KAFKA__PORT:9092"
      - "9101:9101"
    env_file:
      - .env
    environment:
      #KAFKA_LISTENERS: PLAINTEXT://kafka:29092,LISTENER_DOCKER_EXTERNAL://kafka:$KAFKA__PORT
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka}:$KAFKA__PORT
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT      
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:$ZOOKEEPER__PORT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://$LOCAL__HOST:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      #KAFKA_JMX_PORT: 9101
      #KAFKA_JMX_HOSTNAME: localhost
    healthcheck:
      test: nc -z $LOCAL__HOST 9092 || exit -1
      #start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
  
  debezium:
    #image: debezium/connect:latest
    build: ./build
    security_opt:
      - seccomp:unconfined
    restart: always
    container_name: debezium
    hostname: debezium
    env_file:
      - .env
    depends_on:
      - broker
    ports:
      - "$DEBEZIUM__PORT:8083"
    environment:
      BOOTSTRAP_SERVERS: broker:$KAFKA_EXT__PORT
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      #KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      #VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: "true"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "-X", "GET", "http://localhost:8083/connectors"]
      #start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.3
    hostname: schema-registry
    container_name: schema-registry
    env_file:
      - .env
    depends_on:
      - broker
    ports:
      - "$SCHEMA_REG__PORT:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:$KAFKA_EXT__PORT
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

    healthcheck:
      #start_period: 10s
      interval: 10s
      retries: 20
      test: curl --user superUser:superUser --fail --silent --insecure http://localhost:8081/subjects --output /dev/null || exit 1

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.3
    env_file:
      - .env
    depends_on:
      - broker
    ports:
      - "$KAFKA_PROXY_PORT:8082"
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:$KAFKA_EXT__PORT'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"

  debezium-ui:
    image: debezium/debezium-ui:2.2
    restart: always
    container_name: debezium-ui
    hostname: debezium-ui
    env_file:
      - .env
    depends_on:
      - debezium
    ports:
      - "$DEBEZIUM_UI__PORT:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium:$DEBEZIUM__PORT
